"""update_embedding_vector_to_768_dimensions

Revision ID: 062ca8c2dba2
Revises: bea3df00738b
Create Date: 2025-07-13 10:58:43.195770

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '062ca8c2dba2'
down_revision = 'bea3df00738b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, set all existing embedding vectors to NULL to avoid dimension mismatch
    op.execute("UPDATE codesearchembedding SET embedding_vector = NULL WHERE embedding_vector IS NOT NULL")
    
    # Then change the column type from vector(1536) to vector(768)
    op.alter_column('codesearchembedding', 'embedding_vector',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codesearchembedding', 'embedding_vector',
               existing_type=Vector(dim=768),
               type_=Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
