"""add pgvector extension and update embedding_vector to use vector type

Revision ID: bea3df00738b
Revises: d2d88c7427e0
Create Date: 2025-07-12 21:58:23.431782

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'bea3df00738b'
down_revision = 'd2d88c7427e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the pgvector extension if it doesn't exist
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # Convert VARCHAR to VECTOR type with proper casting
    op.execute("""
        ALTER TABLE codesearchembedding 
        ALTER COLUMN embedding_vector TYPE vector(1536) 
        USING CASE 
            WHEN embedding_vector IS NULL THEN NULL
            WHEN embedding_vector = '' THEN NULL
            ELSE embedding_vector::vector(1536)
        END
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert VECTOR back to VARCHAR type
    op.execute("""
        ALTER TABLE codesearchembedding 
        ALTER COLUMN embedding_vector TYPE varchar(10000) 
        USING CASE 
            WHEN embedding_vector IS NULL THEN NULL
            ELSE embedding_vector::text
        END
    """)
    # ### end Alembic commands ###
