"""add_code_search_sessions_table

Revision ID: d2d88c7427e0
Revises: 1a31ce608336
Create Date: 2025-07-12 21:02:36.204576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd2d88c7427e0'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codesearchsession',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vector_embeddings_processed', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codesearchembedding',
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('file_content', sqlmodel.sql.sqltypes.AutoString(length=100000), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('file_metadata', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['codesearchsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codesearchembedding')
    op.drop_table('codesearchsession')
    # ### end Alembic commands ###
